# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environment.yml

sphinx:
  configuration:  docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub